- name: Set up directories
  when: inventory_hostname == groups.master[0]
  file:
    path: "{{ item }}"
    state: directory
    mode: '755'
  loop:
    - "{{ gluster_path }}/recordings"
    - "{{ gluster_path }}/hls"
    - "{{ gluster_path }}/shared-resources"

- import_tasks: rtmp.yml
  when: rtmp_enabled

- import_tasks: srt.yml
  when: srt_enabled


- name: Check stream key mark
  shell: |
    docker run \
      --rm \
      -it \
      --network {{ rtmp_network }} \
      --name redis-cli \
      redis \
      redis-cli GET MARK_GENERATED |\
    grep TRUE
  register: stream_key_generated
  failed_when: false

- name: Generate stream keys
  when: inventory_hostname == groups.master[0] and generate_stream_keys and stream_key_generated.rc != 0
  # No openssl in the redis image so we'll generate keys outside and mount
  # them.
  shell: |
    TMPFILE=$(mktemp)
    for i in $(seq 1 100); do
      openssl rand -hex 32 >> $TMPFILE
    done
    docker run \
      --rm \
      -it \
      --network {{ rtmp_network }} \
      --name redis-cli \
      -v $TMPFILE:/tmp/random-keys \
      redis \
      /bin/sh -c '
      while read line; do
        redis-cli -h redis SET $line $line
      done < /tmp/random-keys
      redis-cli -h redis SET MARK_GENERATED TRUE
      '
