- name: Create docker-compose stack file (on first swarm node)
  when: inventory_hostname == groups.master[0]
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0775'
  loop:
    - src: rtmp/rtmp-stack.yml.j2
      dest: /root/stacks/rtmp-stack.yml

    - src: rtmp/nginx-playback.conf.j2
      dest: "{{ rtmp_playback_proxy_config_path }}"

    - src: rtmp/nginx-ingest.conf.j2
      dest: "{{ rtmp_ingest_proxy_config_path }}"

    - src: rtmp/rtmp-ingest.conf.j2
      dest: "{{ rtmp_ingest_config_path }}"

    - src: rtmp/rtmp-playback.conf.j2
      dest: "{{ rtmp_playback_config_path }}"

    - src: rtmp/rtmp-recording.conf.j2
      dest: "{{ rtmp_recording_config_path }}"


- name: Deploy stack from a compose file (on first swarm node)
  when: inventory_hostname == groups.master[0]
  docker_stack:
    state: present
    name: rtmp
    compose:
      - /root/stacks/rtmp-stack.yml

