debug_certs: false
certs_dry_run: false
generate_stream_keys: true

gluster_path: /mnt/glustershare

recordings_bucket: "rtmp-recordings-bucket"

webhook_url: "{{ secrets.webhook_url }}"

ssl_cert_path: "{{ gluster_path }}/shared-resources/cert"
ssl_key_path: "{{ gluster_path }}/shared-resources/key"

# Keep this in sync with the terraform mount path
recordings_path: /mnt/recordings

app_domain_name: gnomes.moe

# BEGIN: RTMP
rtmp_enabled: true

rtmp_auth_image: "localhost:5000/rtmp-auth"
nginx_rtmp_image: "localhost:5000/nginx-rtmp"
nginx_image: "nginx"

rtmp_redis_data_path: "{{ gluster_path }}/redis"

rtmp_ingest_container: rtmp-ingest
rtmp_recording_container: rtmp-recording
rtmp_playback_container: rtmp-playback

rtmp_ingest_config_path: "{{ gluster_path }}/shared-resources/rtmp-ingest.conf"
rtmp_recording_config_path: "{{ gluster_path }}/shared-resources/rtmp-recording.conf"
rtmp_playback_config_path: "{{ gluster_path }}/shared-resources/rtmp-playback.conf"
rtmp_playback_proxy_config_path: "{{ gluster_path }}/shared-resources/nginx-playback.conf"
rtmp_ingest_proxy_config_path: "{{ gluster_path }}/shared-resources/nginx-ingest.conf"
rtmp_upload_recording_script: "{{ gluster_path }}/shared-resources/upload-to-s3.sh"

rtmp_ingest_replicas: 1
rtmp_recording_replicas: 2
rtmp_playback_replicas: 1

# internal
rtmp_port: 1935
rtmps_port: 1936
rtmp_chunk_size: 4096

rtmp_network: rtmp
rtmp_ingress_port: 1935
rtmps_ingress_port: 1936

rtmp_egress_port: 1937
rtmps_egress_port: 1938

hls_path: "{{ gluster_path }}/hls"
# END: RTMP


# BEGIN: Portainer
portainer_app_name: prt
portainer_agent_secret: "{{ secrets.portainer_agent_secret }}"
portainer_admin_password: "{{ secrets.portainer_admin_password }}"
portainer_admin_port: 9000
portainer_tunnel_port: 8000
portainer_network: portainer
portainer_container_name: portainer
# END: Portainer

# BEGIN: Traefik
traefik_app_name: trfk
traefik_network: traefik
traefik_admin_user: admin
traefik_admin_password: "{{ secrets.traefik_admin_password }}"
traefik_listen_port: 80
traefik_secure_listen_port: 443
traefik_admin_port: 8080
# END: Traefik

# BEGIN: redisinsight
redisinsight_app_name: ri
# END: redisinsight

# BEGIN: Monitor
monitor_network: monitor
node_exporter_container_name: node-exporter
cadvisor_container_name: cadvisor
prometheus_config_path: "{{ gluster_path }}/shared-resources/prometheus/prometheus.yml"
prometheus_data_path: "{{ gluster_path }}/shared-resources/prometheus/data"
prometheus_app_name: prom
grafana_data_path: "{{ gluster_path }}/shared-resources/grafana/data"
grafana_admin_password: "{{ secrets.grafana_admin_password }}"
grafana_app_name: gf
# END: Monitor

# BEGIN: API Keys
porkbun_api_key: "{{ secrets.porkbun_api_key }}"
porkbun_secret_key: "{{ secrets.porkbun_secret_key }}"
# END: API Keys
