- name: Check if registry exists
  shell:
    cmd: "docker service ls | grep registry"
  register: registry
  ignore_errors: true
  changed_when: false

- name: Set up registry
  shell:
    cmd: "docker service create --name registry -p 5000:5000 registry:2"
  when: registry.rc != 0

- name: Set up directory structure
  file:
    path: '/root/docker-build'
    state: directory
    mode: '755'

- name: Copy files
  copy:
    src: "../files/{{ item }}"
    dest: "/root/docker-build/{{ item }}"
  loop:
    # - nginx/
    # - nginx-rtmp/
    - auth-server/

- name: Build images
  community.docker.docker_image_build:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
    outputs:
      - push: true
        type: image
  loop:
    # - name: "{{ nginx_image }}"
      # path: /root/docker-build/nginx
    # - name: "{{ nginx_rtmp_image }}"
      # path: /root/docker-build/nginx-rtmp
    - name: "{{ rtmp_auth_image }}"
      path: /root/docker-build/auth-server

