- name: Set up directories
  when: inventory_hostname == groups.master[0]
  file:
    path: /root/stacks/portainer
    state: directory
    mode: '755'

- name: Generate admin password hash
  when: inventory_hostname == groups.master[0]
  shell: echo $(htpasswd -nBb admin {{portainer_admin_password}}) | cut -d ":" -f 2 | sed -e s/\\$/\\$\\$/g
  register: portainerpassword

- name: Create docker-compose stack file (on first swarm node)
  when: inventory_hostname == groups.master[0]
  template:
    src: portainer-agent-stack.yml.j2
    dest: /root/stacks/portainer-agent-stack.yml
    mode: '0775'

- name: Deploy stack from a compose file (on first swarm node)
  when: inventory_hostname == groups.master[0]
  docker_stack:
    state: present
    name: portainer
    compose:
      - /root/stacks/portainer-agent-stack.yml
