- name: Init swarm
  docker_swarm:
    state: present
    advertise_addr: "{{ advertise_addr }}"
  register: master_swarm_facts

- set_fact:
    worker_join_token: "{{ master_swarm_facts.swarm_facts.JoinTokens.Worker }}"

- name: Set node role
  docker_node:
    hostname: "{{ node_hostname.stdout }}"
    labels:
      ingress: "true"
      authorizer: "true"

