- name: Set up directories
  when: inventory_hostname == groups.master[0]
  file:
    path: /root/stacks/nginx
    state: directory
    mode: '755'

- name: Template files (on first swarm node)
  when: inventory_hostname == groups.master[0]
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0775'
  loop:
    - src: ingress-stack.yml.j2
      dest: /root/stacks/ingress-stack.yml
    - src: nginx.conf.j2
      dest: /root/stacks/nginx/nginx.conf

- name: Deploy stack from a compose file (on first swarm node)
  when: inventory_hostname == groups.master[0]
  docker_stack:
    state: present
    name: ingress
    compose:
      - /root/stacks/ingress-stack.yml

