- name: Set up directories
  when: inventory_hostname == groups.master[0]
  file:
    path: "{{ item }}"
    state: directory
    mode: '755'
  loop:
    - /root/stacks/nginx-rtmp
    - /mnt/rtmp/recordings
    - /mnt/rtmp/hls
    - /mnt/rtmp/shared-resources

- name: Check if stream keys exists
  stat:
    path: "{{ stream_keys_path }}"
  register: stream_keys_result

- name: Remove stream keys
  file:
    path: "{{ stream_keys_path }}"
    state: absent
  when: override_stream_keys and generate_stream_keys and stream_keys_result.stat.exists

- name: Generate stream keys
  shell:
    cmd: "for i in $(seq 1 100); do openssl rand -hex 32 >> {{ stream_keys_path }}; done"
  when: generate_stream_keys and (override_stream_keys or (not stream_keys_result.stat.exists))

- name: Create docker-compose stack file (on first swarm node)
  when: inventory_hostname == groups.master[0]
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0775'
  loop:
    - src: rtmp-stack.yml.j2
      dest: /root/stacks/rtmp-stack.yml
    - src: nginx.conf.j2
      dest: "{{ nginx_rtmp_config_path }}"


- name: Deploy stack from a compose file (on first swarm node)
  when: inventory_hostname == groups.master[0]
  docker_stack:
    state: present
    name: rtmp
    compose:
      - /root/stacks/rtmp-stack.yml
