---
- hosts: all
  name: Common setup
  tags: [common]
  roles: [common]

- hosts: master
  tags: [master-setup]
  roles:
    - swarm-master
    - gluster-master

- hosts: worker
  tags: [worker-setup]
  tasks:
    - set_fact:
        master_facts: "{{ hostvars[groups.master[0]] }}"
    - import_role: name=swarm-worker
    - import_role: name=gluster-worker

- hosts: master
  tags: [prepare]
  roles:
    - build-image
    - certs

- hosts: master
  tags: [deploy]
  roles:
    - traefik
    - portainer
    - monitor
    - stream-stack

- hosts: load-generator
  tags: [generate-load]
  tasks:
    - name: Copy video
      copy:
        src: ../../../videos/squidgameversion.mp4
        dest: /root/video.mp4
    - name: Install load generating dependencies
      apt:
        name:
          - yt-dlp
          - ffmpeg
        update_cache: yes
        state: present
    - name: Generate load
      when: generate_load
      shell: |
        killall ffmpeg || echo "not running"
        bash -c '
        START_INDEX=$(expr {{ loop_index }} * 2)
        PIDS=()

        for i in $(seq 1 1); do
          INDEX=$(expr $START_INDEX + $i)
          ffmpeg -stream_loop -1 -re -i /root/video.mp4 -c:v copy -c:a aac -ar 44100 -ac 1 -f flv rtmp://rtmp.gnomes.moe/live/$INDEX &
          PIDS[${i}]=$!
        done

        for pid in ${PIDS[@]}; do
          wait $pid
        done
        '
      loop: "{{ groups['load-generator'] }}"
      loop_control:
        index_var: loop_index
      failed_when: false

