# GlusterFS stuff
- name: Set base port
  lineinfile:
    path: /etc/glusterfs/glusterd.vol
    regexp: 'option base-port'
    line: "option base-port 49152"

- name: Set max port
  lineinfile:
    path: /etc/glusterfs/glusterd.vol
    regexp: 'option max-port'
    line: "option max-port 49200"

- name: Start and enable GlusterFS service
  service:
    name: glusterd
    state: started
    enabled: true

- name: Check if Gluster volume is initialized
  shell: 
    cmd: "gluster volume list | grep rtmp"
  register: glustervolume
  ignore_errors: true
  changed_when: false

- name: Create Gluster volume
  shell:
    cmd: "gluster volume create rtmp {{ advertise_addr }}:/mnt/rtmp force"
  when: glustervolume.rc != 0
  changed_when: false

- name: Check if Gluster volume is started
  shell:
    cmd: "gluster volume status rtmp"
  register: glustervolume
  ignore_errors: true
  changed_when: false

- name: Start Gluster volume
  shell:
    cmd: "gluster volume start rtmp force"
  when: glustervolume.rc != 0
  changed_when: false

- name: Set up directory structure
  file:
    path: "/mnt/rtmp/{{ item }}"
    state: directory
    mode: '755'
  loop:
    - recordings
    - shared-resources
