- name: Start and enable GlusterFS service
  service:
    name: glusterd
    state: started
    enabled: true

- name: Create mountpoint
  file:
    path: /mnt/rtmp
    state: directory
    mode: '755'

- name: Mount GlusterFS volume
  mount:
    path: /mnt/rtmp
    src: "{{ master_facts.advertise_addr }}:/rtmp"
    fstype: glusterfs
    state: mounted

