networks:
  rtmp:
    driver: bridge

services:
  redis:
    image: redis
    container_name: redis
    networks:
      - rtmp
    ports:
      - 6379:6379

  redisinsight:
    image: redis/redisinsight
    container_name: redisinsight
    networks:
      - rtmp
    ports:
      - 5540:5540

  rtmp-auth:
    container_name: rtmp-auth
    depends_on:
      - redis
    build:
      context: ../iac/ansible/roles/build-image/files/auth-server
    restart: unless-stopped
    environment:
      - PORT=6570
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - rtmp
    volumes:
      - "./stream-keys:/app/stream-keys"

  rtmp-playback:
    image: "tiangolo/nginx-rtmp:latest-2025-01-06"
    container_name: rtmp-playback
    depends_on:
      - rtmp-auth
    restart: unless-stopped
    ports:
      - "1936:1935"
    networks:
      - rtmp
    volumes:
      - "../iac/ansible/roles/stream-stack/templates/rtmp/rtmp-playback.conf:/etc/nginx/nginx.conf"

  rtmp-ingest:
    image: "tiangolo/nginx-rtmp:latest-2025-01-06"
    container_name: rtmp-ingest
    depends_on:
      - rtmp-auth
      - rtmp-playback
    restart: unless-stopped
    ports:
      - "1935:1935"
    networks:
      - rtmp
    volumes:
      - "../iac/ansible/roles/stream-stack/templates/rtmp/rtmp-ingest.conf:/etc/nginx/nginx.conf"

