- name: Check if stream keys exists
  stat:
    path: /mnt/rtmp/shared-resources/stream-keys
  register: stream_keys_result

- name: Remove stream keys
  file:
    path: /mnt/rtmp/shared-resources/stream-keys
    state: absent
  when: override_stream_keys and generate_stream_keys and stream_keys_result.stat.exists


- name: Generate stream keys
  shell:
    cmd: 'for i in $(seq 1 100); do openssl rand -hex 32 >> stream-keys; done'
    chdir: /mnt/rtmp/shared-resources
  when: generate_stream_keys and (override_stream_keys or (not stream_keys_result.stat.exists))

- name: Start stack
  environment:
    RECORDINGS: /mnt/rtmp/recordings
    SSL_CERT: /mnt/rtmp/shared-resources/{{ ssl_cert_name }}
    SSL_KEY: /mnt/rtmp/shared-resources/{{ ssl_key_name }}
    STREAM_KEYS: /mnt/rtmp/shared-resources/stream-keys
    RTMP_AUTH_IMAGE: localhost:5000/rtmp-auth
    NGINX_RTMP_IMAGE: localhost:5000/nginx-rtmp
    NGINX_IMAGE: localhost:5000/nginx
  shell:
    cmd: docker stack deploy -c docker-compose.stack.yml rtmp
    chdir: /root/stack
  changed_when: false

